### ISSUE TITLE
Even more compact mode

### ISSUE THREAD

**Issue by sirbris** [vaadin-component-factory/explorer-tree-grid-flow#8]
Hi,

I can't figure out how to make an even more compact mode.
You already offered this example here: 
https://incubator.virtuallypreinstalled.com/explorer-tree-grid-flow-demo/compact

But where would I need to tweak exactly to shorten the height of each row even further?

```
:host([theme~="compact"]) [part~="cell"] ::slotted(vaadin-grid-cell-content) {
    padding: 1px var(--lumo-space-s); // I changed it to: padding: 0px var(--lumo-space-s);
}
:host([theme~="compact"]) {
    --custom-line-height: 2em; // tried to adjust this to something like 1.2em but did not help
}
```

The goal is to display the rows almost on top of each other... any help would be greatly appreciated :)

Thanks in advance!

**Comment by jcgueriaud1** [comment]
To make the grid more compact, the idea is to reduce the cell with biggest height.
One thing is to reduce the expand icon, then the icon or text in each cell and also the checkbox if the grid is in multiselect. And also reduce the min-height of the row.

**Comment by sirbris** [comment]
Thank you, that helped :)
