### ISSUE TITLE
Update to Vaadin 23

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin-component-factory/explorer-tree-grid-flow#9]
This addon is not working in Vaadin 23.
The effort does not seem to be too big but it requires some investigations

**Comment by sirbris** [comment]
Any updates on this? Can I help in any way?

**Comment by lipisak** [comment]
Hello, is there any progress with this?

Thank you
J

**Comment by F0rce** [comment]
+1

**Comment by jcgueriaud1** [comment]
Unfortunately I didn't have the time to work on this or investigate. I will try to check if the migration effort is ok next week.

**Comment by lipisak** [comment]
Hello,
is there any progress with this issue?

Thx
JS

**Comment by jcgueriaud1** [comment]
Hi, I've just released the v23 branch.

I noticed that there is an issue with theme-for. You can use the part and css variables instead, if some part are missing to style it properly, I will add them.

**Comment by lipisak** [comment]
Thank you very much!

**Comment by Rob-Rocket** [comment]
> Hi, I've just released the v23 branch.
> 
> I noticed that there is an issue with theme-for. You can use the part and css variables instead, if some part are missing to style it properly, I will add them.

It might be, that there is an issue with the ThemableMixin/ThemableElement of Vaadin and (specific) version(s) of LIT - I did a simple LIT component, which isn't working with LIT 2.2.3 / LIT-Element 3.2.0 - but in older LIT versions using ThemableElement   works for my simple component AND the Explorer Tree Grid

**Comment by jcgueriaud1** [comment]
Yes, I think it's related to this ticket: https://github.com/vaadin/web-components/issues/401#issuecomment-1106359285

I would prefer for this component to add more parts if needed and use the standard way to theme a webcomponent. For example: 
```
explorer-tree-grid-toggle::part(toggle) {
....
}
```

or simply the css variables.

**Comment by gmerton-amazon** [comment]
Hi-- I think I'm getting errors as a result of this.  When I run in production mode, I get the error below.  Is this still a work in progress, or am I doing something wrong?  Using vaadin v 23.3.0

[ERROR] 'default' is not exported by frontend/generated/jar-resources/src/explorer-tree-toggle.js?inline, imported by target/frontend/generated-flow-imports-fallback.js
[ERROR] file: C:/Users/Administrator/business-app-starter-flow/target/frontend/generated-flow-imports-fallback.js:7:7
[ERROR] 5: };
[ERROR] 6: import { css, unsafeCSS, registerStyles } from '@vaadin/vaadin-themable-mixin';
[ERROR] 7: import $cssFromFile_0 from 'Frontend/generated/jar-resources/src/explorer-tree-toggle.js?inline';
[ERROR]           ^
[ERROR] 8: const $css_0 = typeof $cssFromFile_0  === 'string' ? unsafeCSS($cssFromFile_0) : $cssFromFile_0;
[ERROR] 9: addCssBlock(`<style>${$css_0}</style>`);
[ERROR] error during build:

**Comment by jcgueriaud1** [comment]
This is an issue with Vite, it's solved in the v23.0.1. It's published in the directory.

**Comment by gmerton-amazon** [comment]
Agreed... I got it working in 24.0.  Many thanks!
